config/routes.rb
Rails.application.routes.draw do
    devise_for :users
    root 'mainforums#index'

    resources :mainforums do
        resources :topics, only: [:new, :create, :edit, :update, :destroy]
    end

    resources :topics, only: [:show] do
        resources :posts
    end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mainforum.rb
class Mainforum < ApplicationRecord
    validates :title, presence: true, length: { minimum: 5 }
    validates :description, presence: true
    has_many :topics
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :topic
end

app/models/topic.rb
class Topic < ApplicationRecord
    validates :title, presence: true, length: { minimum: 5 }
    validates :description, presence: true
    belongs_to :mainforum
    has_many :posts
end

app/models/user.rb
class User < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable

    has_many :mainforums
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    def check_admin!
        redirect_to :back, notice: 'You dont have enough permissions to do that.' unless current_user.try(:admin?)
    end

    def check_user!
        redirect_to "/users/sign_in", notice: 'You need to be logged in to do that.' unless user_signed_in?
    end

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
        def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
        devise_parameter_sanitizer.permit(:account_update, keys: [:username])
    end
end

app/controllers/mainforums_controller.rb
class MainforumsController < ApplicationController
    before_action :find_forum, only: [:show, :edit, :update, :destroy]

    before_filter :check_user!, except: [:index, :show]
    before_filter :check_admin!, except: [:index, :show]

    def index
        @forums = Mainforum.all
    end

    def show
    end

    def new
        @forum = Mainforum.new
    end

    def create
        @forum = Mainforum.new(forum_params)
        @forum.save

        redirect_to @forum
    end

    def edit
    end

    def update
        if @forum.update(forum_params)
            redirect_to @forum, notice: "Forum was successfully updated!"
        else
            render 'edit'
        end
    end

    def destroy
        @forum.destroy

        redirect_to root_path
    end

    private
        def forum_params
            params.require(:mainforum).permit(:title, :description)
        end

        def find_forum
            @forum = Mainforum.find(params[:id])
        end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :find_post, only: [:edit, :update, :destroy]
    before_filter :authenticate_user!, except: [:index, :show]
    
    def index
        @posts = Post.all
    end

    def show
        @post = Post.find(params[:id])
    end

    def new
        @topic = Topic.find(params[:topic_id])
        @post = @topic.posts.build
    end

    def create
        @topic = Topic.find(params[:topic_id])
        @post = @topic.posts.build(post_params)
        @post.save

        redirect_to topic_post_path(@post.topic_id, @post)
    end

    def edit
        @topic = Topic.find(params[:topic_id])

    end

    def update
        if @post.update(post_params)
            redirect_to topic_post_path(@post.topic_id, @post), notice: "Post was successfully updated!"
        else
            render 'edit'
        end
    end

    def destroy
        @post.destroy

        redirect_to topic_path(@post.topic_id)
    end

    private
        def post_params
            params.require(:post).permit(:title, :body)
        end

        def find_post
            @post = Post.find(params[:id])
        end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
    before_action :find_topic, only: [:edit, :update, :destroy]

    before_filter :check_user!, except: [:index, :show]
    before_filter :check_admin!, except: [:index, :show]

    def show
        @topic = Topic.find(params[:id])
    end

    def new
        @forum = Mainforum.find(params[:mainforum_id])
        @topic = @forum.topics.build
    end

    def create
        @forum = Mainforum.find(params[:mainforum_id])
        @topic = @forum.topics.build(topic_params)
        @topic.save

        redirect_to topic_path(@topic)
    end

    def edit
    end

    def update
        if @topic.update(topic_params)
            redirect_to topic_path(@topic), notice: "Topic was successfully updated!"
        else
            render 'edit'
        end
    end

    def destroy
        @topic.destroy

        redirect_to mainforum_path(@forum)
    end

    private
        def topic_params
            params.require(:topic).permit(:title, :description)
        end

        def find_topic
            @forum = Mainforum.find(params[:mainforum_id])
            @topic = @forum.topics.find(params[:id])
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/main_forums_helper.rb
module MainForumsHelper
end

app/helpers/mainforums_helper.rb
module MainforumsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/threads_helper.rb
module ThreadsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Forum</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>

        <nav class="navbar navbar-default">
            <div class="container">
                <div class="navbar-brand">
                    <%= link_to "Home", root_path %>
                </div>

                <% if user_signed_in? %>
                    <ul class="nav navbar-nav navbar-right">
                        <% if current_user.try(:admin?) %>
                            <li>
                                <%= link_to "New Forum", new_mainforum_path %>
                            </li>
                        <% end %>
                        <li>
                            <%= link_to current_user.username, edit_user_registration_path %>
                        </li>
                        <li>
                            <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
                        </li>

                    </ul>

                <% else %>
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <%= link_to "Sign Up", new_user_registration_path %>
                        </li>
                        <li>
                            <%= link_to "Sign In", new_user_session_path %>
                        </li>
                    </ul>
                <% end %>
            </div>
        </nav>

        <div class="container">
            <% flash.each do |name, msg| %>
                <%= content_tag :div, msg, class: "alert" %>
            <% end %>
            <%= yield %>
        </div>
    </body>
</html>

app/views/mainforums/_form.html.erb
<%= form_for @forum do |f| %>
    <p>
        <%= f.label :title %><br />
        <%= f.text_field :title %>
    </p>
    <p>
        <%= f.label :description %><br />
        <%= f.text_area :description %>
    </p>
    <p>
        <%= f.submit %>
    </p>


<% end %>

<%= link_to "Cancel", root_path %>

app/views/mainforums/edit.html.erb
<h1>Edit Forum</h1>

<%= render "form" %>

app/views/mainforums/index.html.erb
<% @forums.each do |forum| %>
    <h1><%= link_to forum.title, forum %><br /></h1>
    <p><%= forum.description %></p>
    <p><%= forum.topics.count %> Threads</p>

    <% postCount = 0 %>
    <% forum.topics.each do |topic| %>
        <% postCount += topic.posts.count %>
    <% end %>
    <p><%= postCount %> Posts</p>

    <hr>
<% end %>

app/views/mainforums/new.html.erb
<h1>New Forum</h1>

<%= render 'form' %>

app/views/mainforums/show.html.erb
<h1><%= @forum.title %></h1>

<%= @forum.description %>
<div style="float: right">
    <%= link_to "Back", root_path %>
    <% if current_user.try(:admin?) %>
        | <%= link_to "Edit", edit_mainforum_path %> |
        <%= link_to "Delete", mainforum_path(@forum), method: :delete, data: { confirm: "Are you sure?" } %>
    <% end %>
</div>

<br>
<br>
<hr />
<% @forum.topics.each do |t| %>
<h3><%= link_to t.title, topic_path(t) %></h3>
<p><%= t.description %></p>
<p><%= t.posts.count %> Posts</p>
<hr>
<% end %>

<% if current_user.try(:admin?) %>
    <%= link_to "New Thread",  new_mainforum_topic_path(@forum, @topic) %>
<% end %>

app/views/posts/_form.html.erb
<%= form_for [@topic, @post] do |p| %>
    <p>
        <%= p.label :title %><br />
        <%= p.text_field :title %>
    </p>
    <p>
        <%= p.label :body %><br />
        <%= p.text_area :body %>
    </p>
    <p>
        <%= p.submit %>
    </p>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
    <h2><%= link_to post.title, post %></h2>
    <p><%= post.body %></p>
    <hr />
<% end %>

<%= link_to "New Post", new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1><br />
<p><%= @post.body %></p>


<br />
<%= link_to "Back", topic_path(@post.topic_id) %> |
<%= link_to "Edit", edit_topic_post_path(@post.topic_id, @post) %> |
<%= link_to "Delete", topic_post_path(@post.topic_id, @post), method: :delete, data: { confirm: "Are you sure?" }  %>

app/views/topics/_form.html.erb
<%= form_for [@forum, @topic] do |t| %>
    <p>
        <%= t.label :title %><br />
        <%= t.text_field :title %>
    </p>
    <p>
        <%= t.label :description %><br />
        <%= t.text_area :description %>
    </p>
    <p>
        <%= t.submit %>
    </p>
<% end %>

app/views/topics/edit.html.erb
<h1>Edit Thread</h1>

<%= render 'form' %>

app/views/topics/new.html.erb
<h1>New Thread</h1>

<%= render 'form' %>

app/views/topics/show.html.erb
<h1><%= @topic.title %></h1>

<p><%= @topic.description %></p>
<div style="float: right">
    <%= link_to "Back", mainforum_path(@topic.mainforum) %>
    <% if current_user.try(:admin?) %>
        | <%= link_to "Edit", edit_mainforum_topic_path(@topic.mainforum, @topic) %> |
        <%= link_to "Delete", mainforum_topic_path(@topic.mainforum, @topic), method: :delete, data: { confirm: "Are you sure?" }  %>
    <% end %>
</div>

<br>
<br>
<hr />
<% @topic.posts.each do |post| %>
    <h3><%= link_to post.title, topic_post_path(@topic, post) %></h3>
    <p><%= post.body %></p>
    <p>Submitted <%= time_ago_in_words(post.created_at) %> ago</p>
    <hr />
<% end %>

<%= link_to "New Post", new_topic_post_path(@topic) %>